language: perl
before_install:
    - cpanm --notest MooseX::FollowPBP File::Slurp XML::Simple FreezeThaw JSON Capture::Tiny Image::PNG::Libpng
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
